# Generated by Django 4.2.9 on 2026-02-07 12:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("home", "0002_gallerypage_galleryimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnouncementIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name": "Announcement Index Page",
                "verbose_name_plural": "Announcement Index Pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="AnnouncementPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Announcement date"
                    ),
                ),
                ("summary", models.CharField(max_length=250)),
                ("body", wagtail.fields.RichTextField()),
            ],
            options={
                "verbose_name": "Announcement Page",
                "verbose_name_plural": "Announcement Pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NewsIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                "verbose_name": "News Index Page",
                "verbose_name_plural": "News Index Pages",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="NewsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="News date")),
                ("intro", models.CharField(max_length=250)),
                ("body", wagtail.fields.RichTextField()),
            ],
            options={
                "verbose_name": "News Page",
                "verbose_name_plural": "News Pages",
            },
            bases=("wagtailcore.page",),
        ),
    ]
